#ifndef MAGIC_BAG
#define MAGIC_BAG
#include "Bag.h"
#include <vector>
#include <string>

/**
 * The derived class from Bag.
 * When you remove an item from the MagicBag, it doesn't leave an empty space.
 * Instead, it magically replaces the item with another random magical item
 *
 * @author Zichen Men <zichen.men@bellevuecollege.edu>
 * @date 10/16/2023
 * @version ___1.0____
 */
template <class ItemType>
class MagicBag : public Bag<ItemType>
{
private:
    static const std::vector<ItemType> magicalItems; // Predefinedlist of magical items
    int randNum;                                     // Random number generated by random number generator

public:
    MagicBag(const int = 10);
    bool removeItem(const ItemType &_item);
};

#include "MagicBag.cpp"

#endif